AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sleep-recorder
  
  Sample SAM Template for sleep-recorder

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  # ApiGatewayApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     Name: ApiGateway-Api
  #     StageName: Prod
  #     Auth:
  #       DefaultAuthorizaer: MyLambdaTokenAuthorizer
  #       Authorizers:
  #         MyLambdaTokenAuthorizer:
  #           FunctionArn: !GetAtt AuthFunction.Arn
  # AuthFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: authorizer/
  #     Handler: authorizer
  #     Runtime: go1.x
  #     Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
  #       Variables:
  #         CHANNEL_ACCESS_TOKEN: HELLO 
  BedinTimeFnction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bedin-time/
      Handler: bedint-time
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies: AmazonDynamoDBFullAccess
      Events:
        Save:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            # RestApiId: !Ref ApiGatewayApi
            Path: /bedin-time/{user_id}
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMODB_ENDPOINT: "http://dynamodb:8000"
          DYNAMODB_TABLE_NAME: SleepRecord
  WakeTimeFnction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: wake-time/
      Handler: wake-time
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies: AmazonDynamoDBFullAccess
      Events:
        Save:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            # RestApiId: !Ref ApiGatewayApi
            Path: /wake-time/{user_id}
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMODB_ENDPOINT: "http://dynamodb:8000"
          DYNAMODB_TABLE_NAME: SleepRecord
  FivedaysRecordFnction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: fivedays-record/
      Handler: fivedays-record
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies: AmazonDynamoDBFullAccess
      Events:
        Save:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            # RestApiId: !Ref ApiGatewayApi
            Path: /{user_id}/record/fivedays
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMODB_ENDPOINT: "http://dynamodb:8000"
          DYNAMODB_TABLE_NAME: SleepRecord
  SleepRecordDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: Date
          AttributeType: String
        - 
          AttributeName": UserID
          AttributeType: String
      KeySchema:
        - 
          AttributeName: Date
          KeyType: HASH
        - 
          AttributeName: UserID
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: SleepRecord
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BedinTimeAPI:
    Description: "API Gateway endpoint URL for Prod environment for BedinTime Fnction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bedin-time/{user_id}"
  BedinTimeFnction:
    Description: "BedinTimeFnction ARN"
    Value: !GetAtt BedinTimeFnction.Arn
  BedinTimeFnctionIamRole:
    Description: "Implicit IAM Role created for BedinTime Fnction"
    Value: !GetAtt BedinTimeFnctionRole.Arn
